### ISSUE TITLE
Install without HACS

### ISSUE THREAD

**Issue by wwelles** [bulldog5046/ha_nespresso_ingetration#13]
Trying to install this without HACS. Is that not possible?

I've added the `/custom_components/nespresso` folder into my HA `/custom_components` in a folder named `ha_nespresso_integration`.

Home Assistant doesn't seem to see it at all as the following returns no log matches, and I see not related entities:
`docker logs homeassistant 2>&1 | grep "nespresso"`

**Comment by wwelles** [comment]
Sorry had a bit of a momentary brain fart and the directory wasn't getting mapped into my docker container correctly.

I'm now seeing it load, and the integration is present.
```2024-01-08 10:02:57.069 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration nespresso which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant```

![image](https://github.com/bulldog5046/ha_nespresso_integration/assets/5238131/9a2e058d-792d-4911-9329-e4bc6efe58d6)

However when I try to add it, I get nothing:
![image](https://github.com/bulldog5046/ha_nespresso_integration/assets/5238131/0e3805c7-5cef-49d0-982c-ebeca0b20920)

**Comment by bulldog5046** [comment]
Is the bluetooth integration enabled and present?

**Comment by wwelles** [comment]
Yes. Am I supposed to do the normal pairing from the Nespresso app while trying to add the device in HA or something?

![image](https://github.com/bulldog5046/ha_nespresso_integration/assets/5238131/9ced40f8-bf79-4809-b482-aa54db878b90)

**Comment by bulldog5046** [comment]
No, if another device is connected to the machine it will not broadcast its bluetooth presence. Depending how you are attempting to use the integration you can either;

If another device is paired but you know the auth_key, disable bluetooth on the other device before attempting to connect this integration and you will be able to provide your auth_key in the onboarding process.

If no other devices are paired to the machine, you should see the device and the integration with generate and install its own auth_key.

**Comment by wwelles** [comment]
There has never been a device paired to it that I'm aware of. It was however a replacement as my original machine broke, so who knows if it was remanufactured. 

Do I have to do something for the machine to enter pairing mode, or is it always looking if nothing else is paired? Should I unplug and replug the Nespresso or something?

**Comment by bulldog5046** [comment]
Which model is it?

**Comment by wwelles** [comment]
My model is: Nespresso Vertuo Next

**Comment by bulldog5046** [comment]
> My model is: Nespresso Vertuo Next

This model isn't currently supported as i don't have one but is being worked on under this feature request. Please feel free to contribute to helping if you are able. I'll close this issue, please refer to the other issue for updates.

https://github.com/bulldog5046/ha_nespresso_integration/issues/12

**Comment by wwelles** [comment]
> > My model is: Nespresso Vertuo Next
> 
> This model isn't currently supported as i don't have one but is being worked on under this feature request. Please feel free to contribute to helping if you are able. I'll close this issue, please refer to the other issue for updates.
> 
> #12

Thank you, will take a look
