### ISSUE TITLE
Pairing Instructions

### ISSUE THREAD

**Issue by hdemel** [bulldog5046/ha_nespresso_ingetration#14]
Couldn't find any instructions on how to pair with this integration. I've installed through HACS but trying to add the integration gives me: "No devices found on network" immediately.

Am I supposed to pair using bluetoothctl on the host first? Or does this pick up the machine over WiFi?

I'm using a Vertuo Pop.

Thanks.

**Comment by hdemel** [comment]
Tried installing the build from: https://github.com/bulldog5046/ha_nespresso_integration/tree/12-device-not-found-even-if-the-machine-is-on-and-was-correctly-linked-to-the-nespresso-app

but I still immediately get "no devices found on the network"

![image](https://github.com/bulldog5046/ha_nespresso_integration/assets/19391691/b28c6b1e-a7e0-4b6e-a603-c4846beefa5b)

The message shows up way too quickly for it to have actually attempted to scan anything. The nespresso is paired with the app and connected to WiFi so I'm not sure what's wrong.

Is there a separate workflow for pairing or is it all handled by the "add integration" workflow of home assistant?

**Comment by bulldog5046** [comment]
Vertuo machines are not currently supported. Please see #12 for any progress.
