### ISSUE TITLE
HACS error, structure is not complient

### ISSUE THREAD

**Issue by yuvalabou** [bulldog5046/ha_nespresso_ingetration#5]
When trying to add this as a custom repository in HACS it throws the following error:

<Integration bulldog5046/ha_nespresso_integration> Repository structure for main is not compliant

My assumption is that it missing the /custom_component/ha_nespresso folder as its structure.

**Comment by bulldog5046** [comment]
Going to leave this pending for now. There are lots a changes require for stability so i'm not ready to make it too easy for people to install and then complain about. More advanced users will figure it out and hopefully give constructive feedback.

**Comment by yuvalabou** [comment]
That's fair enough and I have to agree..

בתאריך יום ה׳, 30 בנוב׳ 2023, 13:11, מאת bulldog5046 ‏<
***@***.***>:

**Comment by bulldog5046** [comment]
Repo has been rebased and updated to be HACS compliant.
